# Wyłapywanie błędów

[[L1. Logowanie|Ten moduł do przerobienia dopiero po przerobieniu całego logowania]]

Jeżeli myśleliście, że skończyliśmy z logowaniem, to jesteście w błędzie. Logowanie wygląda teraz naprawdę fajnie - mamy potrzebne metadane - czas oraz rodzaj logu - oraz correlation id dzieki ktoremu mozemy bez problemu powiazac logi z danym requestem.

Chciałbym Wam pokazać dwa przypadki, w których nasze logi jeszcze zawodzą:

1. Pierwszy case, zobaczmy jakie logi dostaniemy w momencie kiedy ktoś wyśle zapytanie z błędnymi danymi. Zróbmy `make request` z błędnymi wartościami. Klient/server oczywiście dostanie odpowiedź zwrotną ze statusem 422 i informacja co jest złe, ale spójrzmy na to co my mamy w API. Okazuje, się że nie mamy żadnych logów. Oczywiście pojawia się informacja jaka tutaj widzicie:
   `INFO:     127.0.0.1:38058 - "POST /decisions HTTP/1.1" 422 Unprocessable Entity`
   Ale te logi są rzucane przez nasze środowisko uruchomieniowe `uvicorn.run(...)`, który mamy w `if __name__ == "__main__"` i można też skonfigurować logera, który zaimplementowany jest w `uvicorn` po to aby rzucał nam takimi samymi treściami jak nasz `logger` oraz żeby logi z `uvicorn` mogłybyć wysyłane do usługi, w której potem te logi będziemy analizować... ale z mojego punktu widzenia lepiej jest stworzyć własnego logera i go skonfigurować, niż bawić się konfiguracje logerów w konkretnych bibliotekach - z tym jest zdecydowanie za dużo rob